
export type MuscleGroup =
  | "chest"
  | "back"
  | "quads"
  | "hamstrings"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "abs"
  | "glutes"
  | "calves"
  | "forearms";

export const MUSCLE_MAPPING: Record<string, MuscleGroup[]> = {
  // ── Chest ───────────────────────────────────────────────────────────────
  "bench press":                  ["chest", "triceps"],
  "barbell bench press":          ["chest", "triceps"],
  "dumbbell bench press":         ["chest", "triceps"],
  "flat bench press":             ["chest", "triceps"],
  "chest press":                  ["chest", "triceps"],
  "machine chest press":          ["chest", "triceps"],
  "smith machine bench":          ["chest", "triceps"],
  "floor press":                  ["chest", "triceps"],
  "incline bench":                ["chest", "shoulders"],
  "incline press":                ["chest", "shoulders"],
  "incline dumbbell press":       ["chest", "shoulders"],
  "incline barbell press":        ["chest", "shoulders"],
  "incline dumbbell fly":         ["chest"],
  "decline bench":                ["chest", "triceps"],
  "decline press":                ["chest", "triceps"],
  "decline dumbbell press":       ["chest", "triceps"],
  "pushup":                       ["chest", "triceps"],
  "push-up":                      ["chest", "triceps"],
  "wide pushup":                  ["chest"],
  "incline pushup":               ["chest", "triceps"],
  "decline pushup":               ["chest", "triceps"],
  "dumbbell fly":                 ["chest"],
  "cable fly":                    ["chest"],
  "low cable fly":                ["chest"],
  "high cable fly":               ["chest"],
  "cable crossover":              ["chest"],
  "pec dec":                      ["chest"],
  "pec deck":                     ["chest"],
  "chest fly":                    ["chest"],
  "dip":                          ["chest", "triceps"],
  "chest dip":                    ["chest", "triceps"],
  "dumbbell pullover":            ["chest", "back"],
  "cable pullover":               ["chest", "back"],
  "svend press":                  ["chest"],
  "landmine press":               ["chest", "shoulders"],

  // ── Back ────────────────────────────────────────────────────────────────
  "pullup":                       ["back", "biceps"],
  "pull-up":                      ["back", "biceps"],
  "wide grip pullup":             ["back", "biceps"],
  "close grip pullup":            ["back", "biceps"],
  "weighted pullup":              ["back", "biceps"],
  "chin-up":                      ["back", "biceps"],
  "chinup":                       ["back", "biceps"],
  "neutral grip pullup":          ["back", "biceps"],
  "lat pulldown":                 ["back", "biceps"],
  "wide grip lat pulldown":       ["back", "biceps"],
  "close grip lat pulldown":      ["back", "biceps"],
  "single arm lat pulldown":      ["back", "biceps"],
  "straight arm pulldown":        ["back"],
  "row":                          ["back", "biceps"],
  "barbell row":                  ["back", "biceps"],
  "bent over row":                ["back", "biceps"],
  "pendlay row":                  ["back", "biceps"],
  "yates row":                    ["back", "biceps"],
  "t-bar row":                    ["back", "biceps"],
  "cable row":                    ["back", "biceps"],
  "seated row":                   ["back", "biceps"],
  "dumbbell row":                 ["back", "biceps"],
  "single arm row":               ["back", "biceps"],
  "chest supported row":          ["back", "biceps"],
  "meadows row":                  ["back", "biceps"],
  "inverted row":                 ["back", "biceps"],
  "machine row":                  ["back", "biceps"],
  "deadlift":                     ["back", "hamstrings", "glutes"],
  "conventional deadlift":        ["back", "hamstrings", "glutes"],
  "stiff leg deadlift":           ["hamstrings", "glutes", "back"],
  "romanian deadlift":            ["hamstrings", "glutes"],
  "rdl":                          ["hamstrings", "glutes"],
  "single leg rdl":               ["hamstrings", "glutes"],
  "single leg deadlift":          ["hamstrings", "glutes"],
  "sumo deadlift":                ["back", "hamstrings", "glutes"],
  "trap bar deadlift":            ["back", "hamstrings", "glutes", "quads"],
  "hex bar deadlift":             ["back", "hamstrings", "glutes", "quads"],
  "rack pull":                    ["back", "glutes"],
  "shrug":                        ["back", "shoulders"],
  "barbell shrug":                ["back", "shoulders"],
  "dumbbell shrug":               ["back", "shoulders"],
  "face pull":                    ["shoulders", "back"],
  "band pull apart":              ["shoulders", "back"],
  "good morning":                 ["hamstrings", "back"],
  "hyperextension":               ["hamstrings", "back", "glutes"],
  "back extension":               ["hamstrings", "back", "glutes"],
  "ghd":                          ["hamstrings", "back", "glutes"],

  // ── Shoulders ───────────────────────────────────────────────────────────
  "shoulder press":               ["shoulders", "triceps"],
  "military press":               ["shoulders", "triceps"],
  "overhead press":               ["shoulders", "triceps"],
  "ohp":                          ["shoulders", "triceps"],
  "barbell overhead press":       ["shoulders", "triceps"],
  "dumbbell shoulder press":      ["shoulders", "triceps"],
  "seated dumbbell press":        ["shoulders", "triceps"],
  "smith machine shoulder press": ["shoulders", "triceps"],
  "behind the neck press":        ["shoulders", "triceps"],
  "z press":                      ["shoulders", "triceps", "abs"],
  "pike pushup":                  ["shoulders", "triceps"],
  "handstand pushup":             ["shoulders", "triceps"],
  "lateral raise":                ["shoulders"],
  "side raise":                   ["shoulders"],
  "cable lateral raise":          ["shoulders"],
  "machine lateral raise":        ["shoulders"],
  "front raise":                  ["shoulders"],
  "cable front raise":            ["shoulders"],
  "plate front raise":            ["shoulders"],
  "rear delt":                    ["shoulders"],
  "rear delt fly":                ["shoulders", "back"],
  "reverse pec deck":             ["shoulders", "back"],
  "reverse fly":                  ["shoulders", "back"],
  "cable reverse fly":            ["shoulders", "back"],
  "arnold press":                 ["shoulders"],
  "upright row":                  ["shoulders", "biceps"],

  // ── Legs ────────────────────────────────────────────────────────────────
  "squat":                        ["quads", "glutes", "hamstrings"],
  "back squat":                   ["quads", "glutes", "hamstrings"],
  "low bar squat":                ["quads", "glutes", "hamstrings"],
  "high bar squat":               ["quads", "glutes"],
  "front squat":                  ["quads", "glutes"],
  "goblet squat":                 ["quads", "glutes"],
  "sumo goblet squat":            ["quads", "glutes"],
  "hack squat":                   ["quads", "glutes"],
  "smith machine squat":          ["quads", "glutes"],
  "box squat":                    ["quads", "glutes"],
  "pause squat":                  ["quads", "glutes"],
  "landmine squat":               ["quads", "glutes"],
  "sissy squat":                  ["quads"],
  "wall sit":                     ["quads"],
  "split squat":                  ["quads", "glutes"],
  "bulgarian":                    ["quads", "glutes"],
  "bulgarian split squat":        ["quads", "glutes"],
  "step up":                      ["quads", "glutes"],
  "box step up":                  ["quads", "glutes"],
  "lunge":                        ["quads", "glutes"],
  "walking lunge":                ["quads", "glutes"],
  "reverse lunge":                ["quads", "glutes"],
  "lateral lunge":                ["quads", "glutes", "hamstrings"],
  "curtsy lunge":                 ["quads", "glutes"],
  "leg press":                    ["quads", "glutes"],
  "single leg press":             ["quads", "glutes"],
  "leg extension":                ["quads"],
  "leg curl":                     ["hamstrings"],
  "lying leg curl":               ["hamstrings"],
  "seated leg curl":              ["hamstrings"],
  "hamstring curl":               ["hamstrings"],
  "nordic curl":                  ["hamstrings"],
  "hip thrust":                   ["glutes"],
  "barbell hip thrust":           ["glutes"],
  "dumbbell hip thrust":          ["glutes"],
  "glute bridge":                 ["glutes"],
  "single leg glute bridge":      ["glutes"],
  "hip abduction":                ["glutes"],
  "hip adduction":                ["quads"],
  "cable kickback":               ["glutes"],
  "donkey kick":                  ["glutes"],
  "fire hydrant":                 ["glutes"],
  "calf raise":                   ["calves"],
  "standing calf raise":          ["calves"],
  "seated calf raise":            ["calves"],
  "seated calf":                  ["calves"],
  "leg press calf raise":         ["calves"],
  "donkey calf raise":            ["calves"],
  "single leg calf raise":        ["calves"],

  // ── Arms — Biceps ────────────────────────────────────────────────────────
  "bicep curl":                   ["biceps"],
  "biceps curl":                  ["biceps"],
  "barbell curl":                 ["biceps"],
  "ez bar curl":                  ["biceps"],
  "ez curl":                      ["biceps"],
  "dumbbell curl":                ["biceps"],
  "alternating curl":             ["biceps"],
  "hammer curl":                  ["biceps", "forearms"],
  "cross body hammer curl":       ["biceps", "forearms"],
  "pinwheel curl":                ["biceps", "forearms"],
  "preacher curl":                ["biceps"],
  "dumbbell preacher curl":       ["biceps"],
  "concentration curl":           ["biceps"],
  "spider curl":                  ["biceps"],
  "drag curl":                    ["biceps"],
  "cable curl":                   ["biceps"],
  "cable overhead curl":          ["biceps"],
  "incline dumbbell curl":        ["biceps"],
  "bayesian curl":                ["biceps"],
  "wide grip curl":               ["biceps"],
  "zz curl":                      ["biceps"],
  "21s":                          ["biceps"],

  // ── Arms — Triceps ────────────────────────────────────────────────────────
  "tricep extension":             ["triceps"],
  "triceps extension":            ["triceps"],
  "overhead tricep extension":    ["triceps"],
  "overhead dumbbell extension":  ["triceps"],
  "skullcrusher":                 ["triceps"],
  "skull crusher":                ["triceps"],
  "ez bar skullcrusher":          ["triceps"],
  "dumbbell skullcrusher":        ["triceps"],
  "lying tricep extension":       ["triceps"],
  "tricep pushdown":              ["triceps"],
  "triceps pushdown":             ["triceps"],
  "rope pushdown":                ["triceps"],
  "bar pushdown":                 ["triceps"],
  "reverse grip pushdown":        ["triceps"],
  "overhead tricep":              ["triceps"],
  "close grip bench":             ["triceps", "chest"],
  "close grip press":             ["triceps", "chest"],
  "diamond pushup":               ["triceps", "chest"],
  "tricep dip":                   ["triceps"],
  "bench dip":                    ["triceps"],
  "kickback":                     ["triceps"],
  "dumbbell kickback":            ["triceps"],

  // ── Forearms ────────────────────────────────────────────────────────────
  "wrist curl":                   ["forearms"],
  "reverse curl":                 ["forearms", "biceps"],
  "reverse wrist curl":           ["forearms"],
  "reverse barbell curl":         ["forearms", "biceps"],
  "farmer carry":                 ["forearms", "back"],
  "farmer walk":                  ["forearms", "back"],
  "dead hang":                    ["forearms", "back"],
  "grip training":                ["forearms"],
  "plate pinch":                  ["forearms"],
  "towel pullup":                 ["forearms", "back"],

  // ── Core ────────────────────────────────────────────────────────────────
  "crunch":                       ["abs"],
  "bicycle crunch":               ["abs"],
  "reverse crunch":               ["abs"],
  "cable crunch":                 ["abs"],
  "sit-up":                       ["abs"],
  "situp":                        ["abs"],
  "weighted situp":               ["abs"],
  "plank":                        ["abs"],
  "weighted plank":               ["abs"],
  "side plank":                   ["abs"],
  "leg raise":                    ["abs"],
  "hanging leg raise":            ["abs"],
  "toes to bar":                  ["abs"],
  "knee raise":                   ["abs"],
  "hanging knee raise":           ["abs"],
  "ab wheel":                     ["abs"],
  "ab roller":                    ["abs"],
  "russian twist":                ["abs"],
  "mountain climber":             ["abs"],
  "v-up":                         ["abs"],
  "toe touch":                    ["abs"],
  "flutter kick":                 ["abs"],
  "hollow hold":                  ["abs"],
  "hollow body":                  ["abs"],
  "dead bug":                     ["abs"],
  "dragon flag":                  ["abs"],
  "l-sit":                        ["abs"],
  "pallof press":                 ["abs"],
  "cable rotation":               ["abs"],
  "wood chop":                    ["abs", "shoulders"],
  "landmine rotation":            ["abs", "shoulders"],

  // ── Olympic / Power ─────────────────────────────────────────────────────
  "clean":                        ["back", "shoulders", "quads", "glutes"],
  "power clean":                  ["back", "shoulders", "quads", "glutes"],
  "hang clean":                   ["back", "shoulders", "quads", "glutes"],
  "snatch":                       ["back", "shoulders", "quads", "glutes"],
  "power snatch":                 ["back", "shoulders", "quads", "glutes"],
  "hang snatch":                  ["back", "shoulders", "quads", "glutes"],
  "jerk":                         ["shoulders", "quads", "triceps"],
  "clean and jerk":               ["back", "shoulders", "quads", "glutes", "triceps"],
  "thruster":                     ["quads", "glutes", "shoulders", "triceps"],
  "kettlebell swing":             ["glutes", "hamstrings", "back"],
  "single arm kettlebell swing":  ["glutes", "hamstrings", "back"],
  "turkish get up":               ["shoulders", "abs", "glutes"],
  "kettlebell clean":             ["back", "shoulders", "quads", "glutes"],
  "kettlebell snatch":            ["back", "shoulders", "quads", "glutes"],
  "farmer":                       ["back", "abs", "forearms"],
  "sled":                         ["quads", "glutes"],
  "sled push":                    ["quads", "glutes"],
  "sled pull":                    ["quads", "glutes", "hamstrings"],

  // ── Plyometric / Functional ──────────────────────────────────────────────
  "box jump":                     ["quads", "glutes", "calves"],
  "broad jump":                   ["quads", "glutes", "hamstrings"],
  "depth jump":                   ["quads", "glutes", "calves"],
  "plyometric lunge":             ["quads", "glutes"],
  "jump squat":                   ["quads", "glutes", "calves"],
  "battle ropes":                 ["shoulders", "abs"],
  "wall ball":                    ["quads", "glutes", "shoulders"],
  "slam ball":                    ["back", "abs", "shoulders"],
  "medicine ball":                ["abs", "shoulders"],

  // ── Sports (broad muscle group targets) ─────────────────────────────────
  "boxing":                       ["shoulders", "abs", "biceps"],
  "kickboxing":                   ["shoulders", "abs", "quads"],
  "muay thai":                    ["shoulders", "abs", "quads", "calves"],
  "wrestling":                    ["back", "shoulders", "abs", "quads"],
  "judo":                         ["back", "shoulders", "abs"],
  "jiu-jitsu":                    ["back", "shoulders", "abs"],
  "bjj":                          ["back", "shoulders", "abs"],
  "soccer":                       ["quads", "hamstrings", "calves", "glutes"],
  "football":                     ["quads", "hamstrings", "shoulders", "glutes"],
  "basketball":                   ["quads", "calves", "shoulders"],
  "tennis":                       ["shoulders", "abs", "calves"],
  "volleyball":                   ["shoulders", "quads", "calves"],
  "swimming":                     ["back", "shoulders", "chest", "abs"],
  "rowing":                       ["back", "shoulders", "abs", "quads"],
  "crossfit":                     ["back", "shoulders", "quads", "abs"],
};

export function getMusclesFromExercise(exerciseName: string): MuscleGroup[] {
  const lower = exerciseName.toLowerCase();

  // Exact match first
  if (MUSCLE_MAPPING[lower]) return MUSCLE_MAPPING[lower];

  // Keyword search — longest key wins to avoid "row" matching "rowing machine"
  const muscles = new Set<MuscleGroup>();
  const sortedKeys = Object.keys(MUSCLE_MAPPING).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (lower.includes(key)) {
      MUSCLE_MAPPING[key].forEach(g => muscles.add(g));
    }
  }

  return Array.from(muscles);
}
